# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chouti', '0002_auto_20170606_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_news/%Y/%m')),
                ('desc', models.TextField(max_length=200)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chouti.UserInfo')),
            ],
            options={
                'verbose_name': '图片新闻',
                'verbose_name_plural': '图片新闻',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(default='', max_length=500),
        ),
    ]
