# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chouti', '0004_auto_20170606_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenews',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
