# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chouti', '0005_auto_20170607_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenews',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chouti.UserInfo'),
            preserve_default=False,
        ),
    ]
