# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chouti', '0006_imagenews_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='chouti.UserComment'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
